vega_4.1/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vega_4._1.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Registering()
        {
            return View();
        }
    }
}

vega_4.1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vega_4._1.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Firma()
        {
            return View();
        }

        public ActionResult Street()
        {
            return View();
        }

        public ActionResult Network()
        {
            return View();
        }

        public ActionResult Object()
        {
            return View();
        }

        public ActionResult Settings()
        {
            return View();
        }

        public ActionResult Chat()
        {
            return View();
        }

    }
}

vega_4.1/Controllers/LkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vega_4._1.Controllers
{
    public class LkController : Controller
    {
        // GET: Client

        public ActionResult Application()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult History()
        {
            return View();
        }

        public ActionResult Chat()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }

    }
}

vega_4.1/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vega_4._1.Controllers
{
    public class OperatorController : Controller
    {
        // GET: Operator
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult History()
        {
            return View();
        }

        public ActionResult Map()
        {
            return View();
        }

    }
}

vega_4.1/Views/Admin/Chat.cshtml
@{
    Layout = "~/Views/Shared/MainPageAdmin.cshtml";
}

    <div class="chat-lk">

        <div class="header-chat-lk">

            <button id="btn-contacts-lk" class="button-action-chat">

                <i class="fa fa-user" aria-hidden="true"></i>

            </button>

            <div class="wrapper-search-lk">

                <input autocomplete="off" type="text" />

                <button id="search-users-lk" class="button-search-lk">

                    <i class="fa fa-search" aria-hidden="true"></i>

                </button>

                <button id="open-settings-lk" class="button-settings-lk">

                    <i class="fa fa-sliders" aria-hidden="true"></i>

                </button>

            </div>

        </div>

        <div class="body-chat-lk">

            <div id="settings-lk" class="settings-search">

                <div class="name-categories">

                    <span>Поиск по категориям</span>

                    <button id="close-categories-lk" class="close-search-categories">

                        <i class="fa fa-times" aria-hidden="true"></i>

                    </button>

                </div>

                <div class="box-categories">

                    <span>Администраторы</span>

                    <label class="switch">

                        <input type="checkbox">

                        <span class="slider round"></span>

                    </label>

                </div>

                <div class="box-categories">

                    <span>Операторы</span>

                    <label class="switch">

                        <input type="checkbox">

                        <span class="slider round"></span>

                    </label>

                </div>

                <div class="box-categories">

                    <span>Техники</span>

                    <label class="switch">

                        <input type="checkbox">

                        <span class="slider round"></span>

                    </label>

                </div>

                <div class="box-categories">

                    <span>Все</span>

                    <label class="switch">

                        <input type="checkbox">

                        <span class="slider round"></span>

                    </label>

                </div>

            </div>

            <div id="contacts-lk" class="contacts">

                <div class="container-user">

                    <div class="icon-user">



                    </div>

                    <div class="fio-user">

                        <span>ДубровскийХуевский Д. Д.</span>

                    </div>

                    <button class="action">

                        <i class="fa fa-trash" aria-hidden="true"></i>

                    </button>

                    <button class="action">

                        <i class="fa fa-comment-o" aria-hidden="true"></i>

                    </button>

                </div>


            </div>

            <div id="search-lk" class="search-users">

                <div class="container-search-user">

                    <div class="icon-user">



                    </div>

                    <div class="fio-user">

                        <span>БрабажданскийХуевский Д. Д.</span>

                    </div>

                    <button class="action">

                        <i class="fa fa-plus" aria-hidden="true"></i>

                    </button>

                </div>

            </div>

            <div id="box-chat" class="user-chat">

                <div class="message-style buddy-message">

                    <span>Здравствуйте, скажите, пожалуйста, почему у меня моргает маленькая зеленая лампочка на приборе, где написано :"АКБ"?</span>

                </div>

                <div class="message-style my-message">

                    <span>Здравствуйте. Каким цветом моргает?</span>

                </div>

                <div class="message-style buddy-message">

                    <span>Красным</span>

                </div>

                <div class="message-style my-message">

                    <span>Как давно?</span>

                </div>

                <div class="message-style buddy-message">

                    <span>Больше недели</span>

                </div>

                <div class="message-style my-message">

                    <span>Это говорит о пиниженном питании от блока питания. Скорее всего сам блок питания выходит из строя. Нужно проверять на месте, под нагрузкой</span>

                </div>

                <div class="message-style buddy-message">

                    <span>Вы бы могли направить мне электрика?</span>

                </div>

                <div class="message-style my-message">

                    <span>Да, коненчно</span>

                </div>

            </div>

        </div>

        <div class="footer-chat-lk">

            <div class="wrapper-textarea-lk">

                <textarea rows="2" maxlength="999" autocomplete="off" id="" class="" type="text"></textarea>
                <label id="label-app-descript" class="label-textarea" for="app-text-descript">Введите текст</label>

            </div>

            <button id="send-message" class="button-send">

                <i class="fa fa-paper-plane" aria-hidden="true"></i>

            </button>

        </div>

    </div>

vega_4.1/Views/Admin/Firma.cshtml
@{
    Layout = "~/Views/Shared/MainPageAdmin.cshtml";
}

    <div class="box-firma">

        <div class="tabs">

            <input type="radio" name="rbtn" checked value="1" id="tabs-add-firma" /><label for="tabs-add-firma" class="label-tabs">Добавить</label>

            <input type="radio" name="rbtn" value="2" id="tabs-edit-firma" /><label for="tabs-edit-firma" class="label-tabs">Редактировать</label>

            <input type="radio" name="rbtn" value="3" id="tabs-delete-firma" /><label for="tabs-delete-firma" class="label-tabs">Удалить</label>

            <div class="tabs-content-1">

                <form action="#" method="post">

                    <div class="wrapper-input">

                        <input autocomplete="off" id="name-firma" class="" type="text" />
                        <label id="label-name-firma" class="label-input" for="name-firma">Наименование</label>


                    </div>

                    <div class="wrapper-select">

                        <select id="street-firma" class="">

                            <option value="0"></option>

                        </select>

                        <label id="label-street-firma" class="label-select" for="street-firma">Улица</label>

                    </div>

                    <div class="wrapper-input">

                        <input autocomplete="off" id="house-firma" class="" type="text" />
                        <label id="label-house-firma" class="label-input" for="house-firma">Номер дома (и корпуса)</label>


                    </div>

                    <div class="wrapper-input">

                        <input autocomplete="off" id="tel-firma" class="" type="text" />
                        <label id="label-tel-firma" class="label-input" for="tel-firma">Телефон</label>


                    </div>

                    <div class="wrapper-input">

                        <input autocomplete="off" id="email-firma" class="" type="text" />
                        <label id="label-email-firma" class="label-input" for="email-firma">Email</label>


                    </div>

                    <div class="wrapper-button">

                        <button id="btn-conf-create-firma" class="button-admin-style">

                            <i class="fa fa-plus" aria-hidden="true"></i>

                        </button>

                    </div>

                </form>

            </div>

            <div class="tabs-content-2">

                <div class="left-container">

                    <div class="box-search">

                        <form action="#" method="get">

                            <input id="search-firma-edit" class="input-search" type="text" />

                            <button id="btn-search-edit-firma" class="button-search-style"><i class="fa fa-search" aria-hidden="true"></i></button>

                        </form>

                    </div>

                    <div class="box-table">

                        <table class="table-style">

                            <tbody id="tbody-edit-firma" class="tbody-style">

                                <tr id="tr-edit-1">

                                    <td>ООО Рога и копыта jvyvkuyvkuyvk ouyvguyg</td>
                                    <td>ул.В.Интернационалистов, 15-87</td>

                                </tr>

                            </tbody>

                        </table>

                    </div>

                </div>

                <div class="right-container">

                    <form action="#" method="post">

                        <div class="wrapper-input">

                            <input autocomplete="off" id="e-name-firma" class="" type="text" />
                            <label id="label-e-name-firma" class="label-input" for="e-name-firma">Наименование</label>


                        </div>

                        <div class="wrapper-select">

                            <select id="e-street-firma" class="">

                                <option value="0"></option>

                            </select>

                            <label id="label-e-street-firma" class="label-select" for="e-street-firma">Улица</label>

                        </div>

                        <div class="wrapper-input">

                            <input autocomplete="off" id="e-house-firma" class="" type="text" />
                            <label id="label-e-haouse-firma" class="label-input" for="e-house-firma">Номер дома (и корпуса)</label>


                        </div>

                        <div class="wrapper-input">

                            <input autocomplete="off" id="e-tel-firma" class="" type="text" />
                            <label id="label-e-tel-firma" class="label-input" for="e-tel-firma">Телефон</label>


                        </div>

                        <div class="wrapper-input">

                            <input autocomplete="off" id="e-post-firma" class="" type="text" />
                            <label id="label-e-post-firma" class="label-input" for="e-post-firma">Email</label>


                        </div>

                        <div class="wrapper-button">

                            <button id="btn-conf-edit-firma" class="button-admin-style">

                                <i class="fa fa-pencil" aria-hidden="true"></i>

                            </button>

                        </div>

                    </form>

                </div>

            </div>

            <div class="tabs-content-3">

                <div class="left-container">

                    <div class="box-search">

                        <form action="#" method="get">

                            <input id="search-firma-drop" class="input-search" type="text" />

                            <button id="btn-search-delete-firma" class="button-search-style"><i class="fa fa-search" aria-hidden="true"></i></button>

                        </form>

                    </div>

                    <div class="box-table">

                        <table class="table-style">

                            <tbody id="tbody-delete-firma" class="tbody-style">

                                <tr>

                                    <td>ООО Рога и копытаwefwefwefwefwefew wfefewf wfefewfewfewfewf</td>
                                    <td>ул. В.Интернационалистов, 15-87</td>
                                    <td>

                                        <input class="checkbox-style" type="checkbox" />

                                    </td>

                                </tr>

                                <tr>

                                    <td>ОАО Хуйня</td>
                                    <td>ул. В.Интернационалистов, 15-87</td>
                                    <td>

                                        <input class="checkbox-style" type="checkbox" />

                                    </td>

                                </tr>

                            </tbody>

                        </table>

                    </div>

                </div>

                <div class="right-container">

                    <span>Удалить выбранный(-е) объект(-ы)?</span>

                    <div class="wrapper-button">

                        <button id="btn-conf-delete-firma" class="button-admin-style">

                            <i class="fa fa-trash" aria-hidden="true"></i>

                        </button>

                    </div>

                </div>

            </div>

        </div>

    </div>

vega_4.1/Views/Admin/Index.cshtml
@{
    Layout = "~/Views/Shared/MainPageAdmin.cshtml";
}

    <div class="line-flex">

        <div id="info-user" class="container-info">

            <div class="info-circle circle-users">



            </div>

            <span id="count-users" class="count-user">999</span>

        </div>

        <div id="info-operator" class="container-info">

            <div class="info-circle circle-support">



            </div>

            <span id="count-support" class="count-user">999</span>

        </div>

        <div id="info-tech" class="container-info">

            <div class="info-circle circle-worker">



            </div>

            <span id="count-worker" class="count-user">999</span>

        </div>

    </div>

    <div class="line-flex">

        <div class="container-info-tech">

            <div class="header-container-info">

                <span>Техники он-лайн</span>

            </div>

            <div class="body-container-info">

                <div class="container-list-tech">

                    <table class="table-style">

                        <tbody class="tbody-style">

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>
                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                            <tr>

                                <td>ИвановскийХуёвскийТраляля</td>

                            </tr>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>


        <div class="container-info-app">

            <div class="header-container-info">

                <span>Заявки за день</span>

            </div>

            <div class="body-container-info">

                <span class="line-app">Всего: </span>

                <span class="line-app">В работе: </span>

                <span class="line-app" >Выполненные: </span>

                <span class="line-app">От клиентов: </span>

            </div>

        </div>

    </div>

    <div class="line-flex">

        <div class="container-graf">

            <div class="header-container-info">

                <span>Статистика</span>

            </div>

            <div class="body-container-info">



            </div>

        </div>

    </div>

vega_4.1/Views/Admin/Settings.cshtml
@{
    Layout = "~/Views/Shared/MainPageAdmin.cshtml";
}

    <div class="box-settings">

        <div class="box-name-general-settings">

            <span>Доступ из внешней сети</span>

        </div>

        <div class="box-general-settings">

            <span class="span-size-a">Администраторы</span>

            <label class="switch-a">

                <input type="checkbox">

                <span class="slider-a round-a"></span>

            </label>

        </div>

        <div class="box-general-settings">

            <span class="span-size-a">Операторы</span>

            <label class="switch-a">

                <input type="checkbox">

                <span class="slider-a round-a"></span>

            </label>

        </div>

        <div class="box-general-settings">

            <span class="span-size-a">Техники</span>

            <label class="switch-a">

                <input type="checkbox">

                <span class="slider-a round-a"></span>

            </label>

        </div>

        <div class="box-general-settings">

            <span class="span-size-a">Клиенты</span>

            <label class="switch-a">

                <input type="checkbox">

                <span class="slider-a round-a"></span>

            </label>

        </div>

    </div>

vega_4.1/Views/Operator/Map.cshtml
@{
    Layout = "~/Views/Shared/MainPageOperator.cshtml";
}

<div class="main-map">



</div>

vega_4.1/Views/Shared/MainPageOperator.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Content/img/favicon/favicon.ico" type="image/x-icon">
    <title>ОВО ВНГ по г.Новочебоксарску</title>
    @Styles.Render("~/ContentOperator/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="title-admin">

        <div class="mobile-img">



        </div>
        <span class="mobile-warning-text">Не поддерживается</span>

    </div>

    <header class="header-operator">

        <div class="center-block-header-operator">

            <button id="open-menu" class="button-o signal-msg">

                <i class="fa fa-ellipsis-v" aria-hidden="true"></i>

            </button>

            <div class="bell">

                <i class="fa fa-bell" aria-hidden="true"></i>

            </div>

            <div class="message-operator">

                <i class="fa fa-comment" aria-hidden="true"></i>

                <div id="count-msg-o" class="count-message-operator">

                    <span class="number-message-operator">+9</span>

                </div>

            </div>

            <div class="name-operator">

                <div class="box-name-o">

                    <span id="name-o">Иванов Иван Иванович</span>

                </div>

            </div>

            <div class="img-operator">



            </div>

            <div class="output">

                <a href="#"><i class="fa fa-sign-out" aria-hidden="true"></i></a>

            </div>

        </div>

    </header>

    <section class="section-operator">

        <div class="center-block-body-operator">

            <div id="nav-menu" class="nav-menu-operator">

                <button id="close-menu" class="button-o close-nav-menu-operator">

                    <i class="fa fa-times" aria-hidden="true"></i>

                </button>

                <ul class="main-menu-operator">

                    <li>
                        @Html.ActionLink("Главная", "Index", "Operator")
                    </li>

                    <li>
                        @Html.ActionLink("История", "History", "Operator")
                    </li>

                    <li>
                        @Html.ActionLink("Карта", "Map", "Operator")
                    </li>

                </ul>

            </div>

            <div class="column-contacts">

                <div class="header-column">

                    <button id="btn-up-list-tech" class="cursor-column"></button>

                </div>

                <div id="body-list-tech" class="body-column">

                    <div id="list-technics" class="list-contacts">

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б. xwqdqwcqwwqcqwcwc cqwcwqc cwqcwqcwqcwq cwqcwqcwqcwqc</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                        <div class="container-contacts">

                            <div class="row-icon">

                                <div id="" class="wrapper-img">

                                    <div class="count-message">

                                        <span>+99</span>

                                    </div>

                                    <div class="status-contact"></div>

                                </div>

                            </div>

                            <div class="row-fio">

                                <span id="">Брабожданский Б.Б.</span>

                            </div>

                        </div>

                    </div>

                </div>

                <div class="footer-column">

                    <button id="btn-down-list-tech" class="cursor-column"></button>

                </div>

            </div>

            <div id="box-message" class="box-for-write">

                <div class="box-write-header">

                    <button id="close-dialog" class="close-message"></button>

                </div>

                <div class="box-write-body">

                    <div class="list-message">

                        <div class="msg-style bubby-msg">

                            <span class="text-msg">Привет приятель как дела? Чего нового? чем сейчас занят?</span>
                            <span class="time-msg">2019.09.03 в 14:49</span>

                        </div>

                        <div class="msg-style user-msg">

                            <span class="text-msg">Здорова! Да так кручсь-верчусь. Да ничем не занят. Сам как?</span>
                            <span class="time-msg">2019.09.03 в 14:50</span>

                        </div>

                        <div class="msg-style bubby-msg">

                            <span class="text-msg">Да вот работу ищу</span>
                            <span class="time-msg">2019.09.03 в 14:51</span>

                        </div>

                        <div class="msg-style user-msg">

                            <span class="text-msg">?</span>
                            <span class="time-msg">2019.09.03 в 14:53</span>

                        </div>

                        <div class="msg-style user-msg">

                            <span class="text-msg">Совсем плохо? Работа-то есть? Или даже не приглашают на собеседование?</span>
                            <span class="time-msg">2019.09.03 в 14:53</span>
                        </div>

                    </div>

                </div>

                <div class="box-write-footer">

                    <div class="wrapper-textarea-msg">

                        <textarea rows="3" maxlength="512" autocomplete="off" id="message" class="" type="text"></textarea>

                    </div>

                    <button class="send-message">
                    </button>

                </div>

            </div>

            @RenderBody()

        </div>

    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/operator/master")
    @RenderSection("Scripts", required: false)
</body>
</html>